django_codes/mysite/mysite/urls.py
# from books import views
# from books.views import search
# new lines
# from books.views import about_pages
# from django.views.generic.base import TemplateView
from django.conf.urls import url
from django.contrib import admin
# new line
from books.models import Publisher
from django.views.generic.list import ListView


urlpatterns = [
    url(r'^search/$', 'books.views.search'),
    url(r'^admin/', admin.site.urls),
    # new line
    url(r'publishers/$', ListView.as_view(model=Publisher,
                    context_object_name='publisher_list',
                    template_name='books/publisher_list_page.html')),
    ]
    #  url(r'^search-form/$', views.search_form),
    # url(r'^search/$', views.search),
    # url(r'^search/$', search),
    #  new line
    # url(r'^about/$', TemplateView.as_view(template_name='about.html')),
    # url(r'^about/(\w+)/$', about_pages),
  # ]
# from django.conf.urls import patterns, url
# from view import current_datetime, hours_ahead
#
# urlpatterns = patterns('',
#                        url(r'^time/$', current_datetime),
#                        url(r'^time/plus/(\d{1,2})/$', hours_ahead),
#                        )

django_codes/mysite/books/models.py
from __future__ import unicode_literals

from django.db import models


# Create your models here.
class Publisher(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60)
    state_province = models.CharField(max_length=30)
    country = models.CharField(max_length=50)
    website = models.URLField()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]

    class Admin:
        pass


class Author(models.Model):
    salutation = models.CharField(max_length=10)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=40)
    email = models.EmailField('e-mail', blank=True)
    headshot = models.ImageField(upload_to='/tmp', blank=True)

    def __str__(self):
        return '%s %s' % (self.first_name, self.last_name)

    class Admin:
        pass


# new class
class BookManager(models.Manager):
    def title_count(self, keyword):
        return self.filter(title__icontains=keyword).count()


class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField(Author)
    publisher = models.ForeignKey(Publisher)
    publication_date = models.DateField(blank=True, null=True)
    num_pages = models.IntegerField(blank=True, null=True)
    objects = BookManager()      # new line

    def __str__(self):
        return self.title

    class Admin:
        list_display = ('title', 'publisher', 'publication_date')
        list_filter = ('publisher', 'publication_date')
        ordering = ('-publication_date',)
        search_fields = ('title',)

django_codes/mysite/contact/forms.py
from django import forms


class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    email = forms.EmailField(required=False, label='Your e-mail address')
    message = forms.CharField(widget=forms.Textarea)

    def clean_message(self):
        message = self.cleaned_data['message']
        num_words = len(message.split())
        if num_words < 4:
            raise forms.ValidationError("Not enough words!")
        return message

django_codes/mysite/books/views.py
# from django.http import Http404
# from django.template import TemplateDoesNotExist
# from django.views.generic.base import TemplateView
from django.shortcuts import render_to_response, HttpResponse
from books.models import Book


# Create your views here.
def search(request):
    errors = []
    if 'q' in request.GET:
        q = request.GET['q']
        if not q:
            errors.append('Enter a search term.')
        elif len(q) > 20:
            errors.append('Please enter at most 20 characters.')
        else:
            books = Book.objects.filter(title__icontains=q)
            return render_to_response('books/search_results.html',
                {'books': books, 'query': q})
    return render_to_response('books/search_form.html',
                                {'errors': errors})
# def search_form(request):
#     return render_to_response('books/search_form.html')
#  def about_pages(request, page):
#     try:
#         return TemplateView.as_view(request, template="about/%s.html" % page)
#     except TemplateDoesNotExist:
#         raise Http404()

django_codes/mysite/contact/views.py
from django.shortcuts import render_to_response, HttpResponseRedirect
from django.core.mail import send_mail
from contact.forms import ContactForm


# Create your views here.
# def search_form(request):
#     return render_to_response('books/search_form.html')


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            send_mail(
                cd['subject'],
                cd['message'],
                cd.get('email', '1374778773@qq.com'),
                ['1003715945@qq.com'],
            )
            return HttpResponseRedirect('/contact/thanks/')
    else:
        form = ContactForm(initial={'subject': 'I love your site!'})
    return render_to_response('contact/contact_form.html', {'form': form})

django_codes/mysite/books/templates/books/publisher_list_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{#{% extends "base.html" %}#}
{% block content %}
    <h2>Publishers</h2>
    <ul>
        {% for publisher in object_list %}
            <li>{{ publisher.name }}</li>
        {% endfor %}
    </ul>
{% endblock %}
</body>
</html>

django_codes/mysite/books/templates/books/search_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Search</title>
</head>
<body>
{% if errors %}
    <ul>
        {% for error in errors %}
            <li>{{ error }}</li>
        {% endfor %}
    </ul>
{% endif %}
<form action="/search/" method="get">
        <input type="text" name="q">
        <input type="submit" value="Search">
    </form>
</body>
</html>

django_codes/mysite/books/templates/books/search_results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>You searched for: <strong>{{ query }}</strong></p>

{% if books %}
    <p>Found {{ books|length }} book{{ books|pluralize }}.</p>
    <ul>
        {% for book in books %}
        <li>{{ book.title }}</li>
        {% endfor %}
    </ul>
{% else %}
    <p>No books matched your search criteria.</p>
{% endif %}
</body>
</html>

django_codes/mysite/contact/templates/contact/contact_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Contact us</title>
</head>
<body>
 <h1>Contact us</h1>

    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}

    <form action="" method="post">
        <div class="field">
            {{ form.subject.errors }}
            <label for="id_subject">Subject:</label>
            {{ form.subject }}
        </div>
        <div class="field">
            {{ form.email.errors }}
            <label for="id_email">Your e-mail address:</label>
            {{ form.email }}
        </div>
        <div class="field">
            {{ form.message.errors }}
            <label for="id_message">Message:</label>
            {{ form.message }}
        </div>
        <input type="submit" value="Submit">
    </form>
</body>
</html>